name: node js git hub action 
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  job1:
    strategy:
      matrix:
        operating_systems: [windows-latest, ubuntu-latest]
        node_version: [20, 24]
        exclude:
         - operating_systems: windows-latest
           node_version: 24
         - operating_systems: ubuntu-latest
           node_version: 20
    runs-on: ${{matrix.operating_systems}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: setups node js
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node_version}}
          cache: npm
      - name: setup prerequisite
        run: npm ci
      - name: run tests
        run: npm test
