name: node js project demo
on:
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v6
      - name: setup node js
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: 'npm'
      - name: Install node depenencies
        run: npm ci
      - name: Execute test cases
        run: npm test
      - name: Build the node js code
        run: npm run build
  
  

    
