name: node js git hub action 
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: setups node js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: setup prerequisite
        run: npm ci
      - name: run tests
        run: npm test
