name: node js project demo
on:
  workflow_dispatch:
  push:
   branches: 
     - master
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: clone repo
        uses: actions/checkout@v6
      - name: setup nodejs
        uses: actions/setup-node@v6 
      - name: install node dependencies
        run: npm ci
      - name: Execute tests
        run: npm test
      - name: Build artifacts
        run: npm run build
